### ISSUE TITLE
VDS names mixed case handling

### ISSUE THREAD

**Issue by spireitepaul** [fabrice-etanchaud/dbt-dremio#20]
Hi,

I suspect this is related to https://github.com/fabrice-etanchaud/dbt-dremio/issues/17

I have several models, and the object names are things like "mydata"."cs_CompanyStatus"

When I run 'dbt run', the first time, everything is great.

When I rerun, I get the same error as in issue 17.

  When searching for a relation, dbt found an approximate match. Instead of guessing
  which relation to use, dbt will move on. Please delete "mydata"."cs_companystatus", or rename it to be less ambiguous.
  Searched for: "mydata"."cs_CompanyStatus"
  Found: "mydata"."cs_companystatus"

but in the Dremio UI, in the mydata Space, the object is called cs_CompanyStatus

Is this really the same issue?

I did notice that a SELECT  * FROM "mydata"."cs_CompanyStatus" worked, as did SELECT * FROM "mydata"."cs_companystatus", implying that Dremio is case insensitive here as well.

**Comment by fabrice-etanchaud** [comment]
Hi @spireitepaul , could you please a log of the run ? A select * from information_schema."tables" and information_schema.views could help.

**Comment by aaroncwhite** [comment]
Chiming in here since it's also happening to me.  I've found several posts from DBT saying "just don't use mix case names".  Like [this one](https://github.com/dbt-labs/dbt-core/issues/1557) 

When dbt does it's first schema lookup at the start of a run it runs a `lower` on all of the database, schema, table names which I believe is why it's failing.  Here's what fails in my logs:

```
    with schemata as (
        select lower(case when position('.' in schema_name) > 0
                then substring(schema_name, 1, position('.' in schema_name) - 1)
                else schema_name
            end) as catalog_name
            ,lower(case when position('.' in schema_name) > 0
                then substring(schema_name, position('.' in schema_name) + 1)
                else 'no_schema'
            end) as schema_name
        from information_schema.schemata
    )
    select distinct schema_name
    from schemata
    where ilike(catalog_name, 'Production-dbt')
      -- and schema_name <> 'no_schema'
```

This is running a macro from the [adapters.sql](https://github.com/fabrice-etanchaud/dbt-dremio/blob/ca845af2b17a63543ee00484046c929ef42ade46/dbt/include/dremio/macros/adapters.sql#L123) set of macros.  It's also running `lower` in the table name lookups from what I can tell [here](https://github.com/fabrice-etanchaud/dbt-dremio/blob/ca845af2b17a63543ee00484046c929ef42ade46/dbt/include/dremio/macros/adapters.sql#L167).  

I've gotten around this by using lower case names.

**Comment by fabrice-etanchaud** [comment]
Hi @aaroncwhite , next dbt-dremio version will not lowercase identifiers anymore, i propose to close this issue.
Please keep in touch, and tell me if you experience new problems.
Best,
